sonar.organization=abirkheire
sonar.projectKey=Usine_Logicielle_Ecommerce

sonar.sources=auth/src,product/src,order/src,api-gateway

sonar.javascript.lcov.reportPaths=\
  coverage-reports/coverage-auth/lcov.info,\
  coverage-reports/coverage-product/lcov.info,\
  coverage-reports/coverage-order/lcov.info,\
  coverage-reports/coverage-api-gateway/lcov.info

sonar.exclusions=**/node_modules/**,**/coverage/**